USE TREINO3
IF EXISTS(SELECT * FROM SYS.OBJECTS WHERE TYPE = 'P' AND OBJECT_ID = OBJECT_ID('AA_SP_BUSCAUSUARIO'))
BEGIN
	DROP PROCEDURE AA_SP_BUSCAUSUARIO
END
GO
CREATE PROCEDURE AA_SP_BUSCAUSUARIO @ID INT
AS
BEGIN
	SELECT * FROM [USER] WHERE ID = @ID
END
